apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketflow-config
  namespace: ticketflow
  labels:
    app.kubernetes.io/name: ticketflow
    app.kubernetes.io/component: config
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  USER_SERVICE_URL: http://user-service:3001
  EVENT_SERVICE_URL: http://event-service:3002
  BOOKING_SERVICE_URL: http://booking-service:3003
  INVENTORY_SERVICE_URL: http://inventory-service:3004
  PAYMENT_SERVICE_URL: http://payment-service:3005
  NOTIFICATION_SERVICE_URL: http://notification-service:3006
  SMTP_HOST: mailpit
  SMTP_PORT: "1025"
  SMTP_FROM: noreply@ticketflow.com
  PAYMENT_SUCCESS_RATE: "0.95"
  DB_USERNAME: postgres
  MONGO_DB_PREFIX: ticketflow
